#!/bin/bash

set -xe

(
    # TODO Fix HOME_DIR being something like '/Users/frosasbosque/src/dotfiles 
    # /Users/frosasbosque/src/dotfiles/home' because the CDPATH
    HOME_DIR=$(cd $(dirname $0) && pwd)/home
    (cd ~ && find $HOME_DIR -depth 1 -exec ln -s {} \;)
    if [[ `uname` = Darwin ]]; then
        (cd ~/Library/Preferences && ln -s $HOME_DIR/Library/Preferences/*)
    fi
)

vim +BundleInstall +qall # See https://github.com/gmarik/vundle

if [ `uname` = Darwin ]; then 

    # From https://github.com/mathiasbynens/dotfiles/blob/master/.osx

    # Disable Notification Center and remove the menu bar icon
    launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist

    # Disable press-and-hold for keys in favor of key repeat
    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

    # Set a blazingly fast keyboard repeat rate
    defaults write NSGlobalDomain KeyRepeat -int 0

    # Trackpad: enable tap to click for this user and for the login screen
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
    defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

    # Display full POSIX path as Finder window title
    defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

    ###

    (
        brew install bash-completion node the_silver_searcher trash wget git ag \
            npm caskroom/cask/brew-cask tree
        true
    )

    # MacVim
    brew install macvim --override-system-vim
    brew linkapps
    (cp -aH /Applications/MacVim.app ~/Applications/; true)

    APPS="atom boom ccmenu firefox gimp google-chrome iterm2 kdiff3 skype slate sourcetree spotify the-unarchiver battery-time-remaining"
    for APP in $APPS; do
        (brew cask install $APP; true)
    done
fi

npm install -g jshint
