#!/bin/sh

# Symlink (or move) this file to an empty directory and execute it to run 
# Google Chrome under a new profile.

CHROME=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
CURRENT_DIR="`dirname \"$0\"`"

exec "$CHROME" --user-data-dir="$CURRENT_DIR" "$@"
