" Appearance
syntax on
set nowrap
set linebreak
set showcmd

" Tabs
set tabstop=4
set shiftwidth=4
set expandtab

" Indent
set autoindent
set smartindent

" Searching
set ignorecase
set smartcase
set incsearch

" Specific file types configuration
filetype on
filetype plugin on
