#!/bin/bash

set -xe

HERE=$(cd $(dirname $0) >/dev/null && pwd)

$HERE/home
$HERE/vim

if [[ `uname` = Darwin ]]; then 
	$HERE/mac-preferences
	brew bundle --global
	$HERE/iterm
	$HERE/ruby
fi

$HERE/npm
