#!/bin/bash

set -xe

HERE=$(cd $(dirname $0) >/dev/null && pwd)

$HERE/home
$HERE/vim

if [[ `uname` = Darwin ]]; then 
    $HERE/mac-preferences
    $HERE/brew
    $HERE/iterm
    $HERE/ruby
fi

$HERE/node
