#!/bin/bash

set -xe

HERE=$(cd $(dirname $0) >/dev/null && pwd)

$HERE/symlinks
$HERE/vim

if [[ `uname` = Darwin ]]; then 
    $HERE/mac-preferences
    $HERE/brew
    $HERE/cask
    $HERE/iterm
fi

$HERE/node
