#!/bin/bash

set -xe

for tap in $(cat "$(dirname $0)/brew-taps"); do brew tap $tap; done
# Install casks first as "java" (a cask) is required by "plantuml"
brew cask install $(cat "$(dirname $0)/brew-cask-formulas") || true
brew install $(cat "$(dirname $0)/brew-formulas") || true
