#!/bin/bash

set -ex

DOTFILES_HOME=$(cd $(dirname $0) >/dev/null && pwd)/../home

symlink_home_dir_files () {
    DIR="$1" # Path relative to home
    mkdir -p "$HOME/$DIR"
    (cd "$HOME/$DIR" && ln -s "$DOTFILES_HOME/$DIR"/*)
}

(
    # TODO Link only the files and create the dirs if they don't exist
    (cd ~ && find $DOTFILES_HOME -depth 1 -exec ln -s {} \;)
    if [[ `uname` = Darwin ]]; then
        symlink_home_dir_files "Library/Application Support/Spectacle"
        symlink_home_dir_files "Library/LaunchAgents"
    fi
)
