#!/bin/bash

set -xe

# From https://github.com/mathiasbynens/dotfiles/blob/master/.osx and
# https://github.com/geerlingguy/dotfiles/blob/master/.osx

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Save screenshots to Downloads
defaults write com.apple.screencapture location -string "${HOME}/Downloads"

#
# Preferences
#

# Keyboard → Keyboard → Key Repeat
defaults write NSGlobalDomain KeyRepeat -int 1

# Keyboard → Keyboard → Delay Until Repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 20

# Accessibility → Mouse & Trackpad → Trackpad options → Enable dragging → three finger drag
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -int 1

#
# Finder
#

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

#
# Dock
#

defaults write com.apple.dock autohide -int 1

defaults write com.apple.dock show-recents -int 0

killall Dock

#
# Flux
#

defaults write org.herf.Flux offlineMode -int 1
defaults write org.herf.Flux wakeNotifyDisable -int 1