#!/bin/bash

set -ex

HOME_DIR=$(cd $(dirname $0) >/dev/null && pwd)/../home

(
    # TODO Link only the files and create the dirs if they don't exist
    (cd ~ && find $HOME_DIR -depth 1 -exec ln -s {} \;)
    (ln -s $HOME_DIR/.ssh/config ~/.ssh || true)
    if [[ `uname` = Darwin ]]; then
        (cd ~/Library/Preferences && ln -s $HOME_DIR/Library/Preferences/* || true)
        (cd ~/Library/Application\ Support && ln -s $HOME_DIR/Library/Application\ Support/* || true)
    fi
)
